/* eslint-disable import/max-dependencies */
import "./test/array.js"
import "./test/boolean.js"
import "./test/date.js"
import "./test/error.js"
import "./test/function-arrow"
import "./test/instance.js"
import "./test/null.js"
import "./test/number.js"
import "./test/object.js"
import "./test/regexp.js"
import "./test/string.js"
import "./test/symbol.js"
import "./test/undefined.js"
